title: Sumanth Yalamarty
include: ["_pages"]
exclude:
  [
    "_includes/notes_graph.json",
    "_includes/link-previews.html",
    "_plugins/last_modified_at_generator.rb",
  ]
baseurl: ""

use_html_extension: false
open_external_links_in_new_tab: true
embed_tweets: false

permalink: pretty
relative_permalinks: false

markdown: kramdown
mathjax: true

sass:
  sass_dir: _sass
  style: "compressed"

collections:
  notes:
    output: true
    permalink: "/:path"
  ldocs:
    output: true

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
